<?php

namespace Database\Seeders;

use App\Models\Ciudad;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ciuadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ciudad::create(['nombre' => 'Bogotá', 'status' => true]);
        Ciudad::create(['nombre' => 'MEDELLIN', 'status' => true]);
        Ciudad::create(['nombre' => 'ABEJORRAL', 'status' => true]);
        Ciudad::create(['nombre' => 'ABRIAQUI', 'status' => true]);
        Ciudad::create(['nombre' => 'ALEJANDRIA', 'status' => true]);
        Ciudad::create(['nombre' => 'AMAGA', 'status' => true]);
        Ciudad::create(['nombre' => 'AMALFI', 'status' => true]);
        Ciudad::create(['nombre' => 'ANDES', 'status' => true]);
        Ciudad::create(['nombre' => 'ANGELOPOLIS', 'status' => true]);
        Ciudad::create(['nombre' => 'ANGOSTURA', 'status' => true]);
        Ciudad::create(['nombre' => 'ANORI', 'status' => true]);
        Ciudad::create(['nombre' => 'ANTIOQUIA', 'status' => true]);
        Ciudad::create(['nombre' => 'ANZA', 'status' => true]);
        Ciudad::create(['nombre' => 'APARTADO', 'status' => true]);
        Ciudad::create(['nombre' => 'ARBOLETES', 'status' => true]);
        Ciudad::create(['nombre' => 'ARGELIA', 'status' => true]);
        Ciudad::create(['nombre' => 'ARMENIA', 'status' => true]);
        Ciudad::create(['nombre' => 'BARBOSA', 'status' => true]);
        Ciudad::create(['nombre' => 'BELMIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'BELLO', 'status' => true]);
        Ciudad::create(['nombre' => 'BETANIA', 'status' => true]);
        Ciudad::create(['nombre' => 'BETULIA', 'status' => true]);
        Ciudad::create(['nombre' => 'BOLIVAR', 'status' => true]);
        Ciudad::create(['nombre' => 'BRICEÑO', 'status' => true]);
        Ciudad::create(['nombre' => 'BURITICA', 'status' => true]);
        Ciudad::create(['nombre' => 'CACERES', 'status' => true]);
        Ciudad::create(['nombre' => 'CAICEDO', 'status' => true]);
        Ciudad::create(['nombre' => 'CALDAS', 'status' => true]);
        Ciudad::create(['nombre' => 'CAMPAMENTO', 'status' => true]);
        Ciudad::create(['nombre' => 'CAÑASGORDAS', 'status' => true]);
        Ciudad::create(['nombre' => 'CARACOLI', 'status' => true]);
        Ciudad::create(['nombre' => 'CARAMANTA', 'status' => true]);
        Ciudad::create(['nombre' => 'CAREPA', 'status' => true]);
        Ciudad::create(['nombre' => 'CARMEN DE VIBORAL', 'status' => true]);
        Ciudad::create(['nombre' => 'CAROLINA', 'status' => true]);
        Ciudad::create(['nombre' => 'CAUCASIA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIGORODO', 'status' => true]);
        Ciudad::create(['nombre' => 'CISNEROS', 'status' => true]);
        Ciudad::create(['nombre' => 'COCORNA', 'status' => true]);
        Ciudad::create(['nombre' => 'CONCEPCION', 'status' => true]);
        Ciudad::create(['nombre' => 'CONCORDIA', 'status' => true]);
        Ciudad::create(['nombre' => 'COPACABANA', 'status' => true]);
        Ciudad::create(['nombre' => 'DABEIBA', 'status' => true]);
        Ciudad::create(['nombre' => 'DON MATIAS', 'status' => true]);
        Ciudad::create(['nombre' => 'EBEJICO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL BAGRE', 'status' => true]);
        Ciudad::create(['nombre' => 'ENTRERRIOS', 'status' => true]);
        Ciudad::create(['nombre' => 'ENVIGADO', 'status' => true]);
        Ciudad::create(['nombre' => 'FREDONIA', 'status' => true]);
        Ciudad::create(['nombre' => 'FRONTINO', 'status' => true]);
        Ciudad::create(['nombre' => 'GIRALDO', 'status' => true]);
        Ciudad::create(['nombre' => 'GIRARDOTA', 'status' => true]);
        Ciudad::create(['nombre' => 'GOMEZ PLATA', 'status' => true]);
        Ciudad::create(['nombre' => 'GRANADA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUADALUPE', 'status' => true]);
        Ciudad::create(['nombre' => 'GUARNE', 'status' => true]);
        Ciudad::create(['nombre' => 'GUATAPE', 'status' => true]);
        Ciudad::create(['nombre' => 'HELICONIA', 'status' => true]);
        Ciudad::create(['nombre' => 'HISPANIA', 'status' => true]);
        Ciudad::create(['nombre' => 'ITAGUI', 'status' => true]);
        Ciudad::create(['nombre' => 'ITUANGO', 'status' => true]);
        Ciudad::create(['nombre' => 'JARDIN', 'status' => true]);
        Ciudad::create(['nombre' => 'JERICO', 'status' => true]);
        Ciudad::create(['nombre' => 'LA CEJA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA ESTRELLA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA PINTADA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA UNION', 'status' => true]);
        Ciudad::create(['nombre' => 'LIBORINA', 'status' => true]);
        Ciudad::create(['nombre' => 'MACEO', 'status' => true]);
        Ciudad::create(['nombre' => 'MARINILLA', 'status' => true]);
        Ciudad::create(['nombre' => 'MONTEBELLO', 'status' => true]);
        Ciudad::create(['nombre' => 'MURINDO', 'status' => true]);
        Ciudad::create(['nombre' => 'MUTATA', 'status' => true]);
        Ciudad::create(['nombre' => 'NARIÑO', 'status' => true]);
        Ciudad::create(['nombre' => 'NECOCLI', 'status' => true]);
        Ciudad::create(['nombre' => 'NECHI', 'status' => true]);
        Ciudad::create(['nombre' => 'OLAYA', 'status' => true]);
        Ciudad::create(['nombre' => 'PEÑOL', 'status' => true]);
        Ciudad::create(['nombre' => 'PEQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'PUEBLORRICO', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO BERRIO', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO NARE (LA MAGDALENA)', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO TRIUNFO', 'status' => true]);
        Ciudad::create(['nombre' => 'REMEDIOS', 'status' => true]);
        Ciudad::create(['nombre' => 'RETIRO', 'status' => true]);
        Ciudad::create(['nombre' => 'RIONEGRO', 'status' => true]);
        Ciudad::create(['nombre' => 'SABANALARGA', 'status' => true]);
        Ciudad::create(['nombre' => 'SABANETA', 'status' => true]);
        Ciudad::create(['nombre' => 'SALGAR', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ANDRES', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN CARLOS', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN FRANCISCO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JERONIMO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JOSE DE LA MONTAÑA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JUAN DE URABA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN LUIS', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN PEDRO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN PEDRO DE URABA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN RAFAEL', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ROQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN VICENTE', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA BARBARA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA ROSA DE OSOS', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTO DOMINGO', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTUARIO', 'status' => true]);
        Ciudad::create(['nombre' => 'SEGOVIA', 'status' => true]);
        Ciudad::create(['nombre' => 'SONSON', 'status' => true]);
        Ciudad::create(['nombre' => 'SOPETRAN', 'status' => true]);
        Ciudad::create(['nombre' => 'TAMESIS', 'status' => true]);
        Ciudad::create(['nombre' => 'TARAZA', 'status' => true]);
        Ciudad::create(['nombre' => 'TARSO', 'status' => true]);
        Ciudad::create(['nombre' => 'TITIRIBI', 'status' => true]);
        Ciudad::create(['nombre' => 'TOLEDO', 'status' => true]);
        Ciudad::create(['nombre' => 'TURBO', 'status' => true]);
        Ciudad::create(['nombre' => 'URAMITA', 'status' => true]);
        Ciudad::create(['nombre' => 'URRAO', 'status' => true]);
        Ciudad::create(['nombre' => 'VALDIVIA', 'status' => true]);
        Ciudad::create(['nombre' => 'VALPARAISO', 'status' => true]);
        Ciudad::create(['nombre' => 'VEGACHI', 'status' => true]);
        Ciudad::create(['nombre' => 'VENECIA', 'status' => true]);
        Ciudad::create(['nombre' => 'VIGIA DEL FUERTE', 'status' => true]);
        Ciudad::create(['nombre' => 'YALI', 'status' => true]);
        Ciudad::create(['nombre' => 'YARUMAL', 'status' => true]);
        Ciudad::create(['nombre' => 'YOLOMBO', 'status' => true]);
        Ciudad::create(['nombre' => 'YONDO', 'status' => true]);
        Ciudad::create(['nombre' => 'ZARAGOZA', 'status' => true]);
        Ciudad::create(['nombre' => 'BARRANQUILLA (DISTRITO ESPECIAL INDUSTRIAL Y PORTUARIO DE BARRANQUILLA)', 'status' => true]);
        Ciudad::create(['nombre' => 'BARANOA', 'status' => true]);
        Ciudad::create(['nombre' => 'CAMPO DE LA CRUZ', 'status' => true]);
        Ciudad::create(['nombre' => 'CANDELARIA', 'status' => true]);
        Ciudad::create(['nombre' => 'GALAPA', 'status' => true]);
        Ciudad::create(['nombre' => 'JUAN DE ACOSTA', 'status' => true]);
        Ciudad::create(['nombre' => 'LURUACO', 'status' => true]);
        Ciudad::create(['nombre' => 'MALAMBO', 'status' => true]);
        Ciudad::create(['nombre' => 'MANATI', 'status' => true]);
        Ciudad::create(['nombre' => 'PALMAR DE VARELA', 'status' => true]);
        Ciudad::create(['nombre' => 'PIOJO', 'status' => true]);
        Ciudad::create(['nombre' => 'POLO NUEVO', 'status' => true]);
        Ciudad::create(['nombre' => 'PONEDERA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO COLOMBIA', 'status' => true]);
        Ciudad::create(['nombre' => 'REPELON', 'status' => true]);
        Ciudad::create(['nombre' => 'SABANAGRANDE', 'status' => true]);
        Ciudad::create(['nombre' => 'SABANALARGA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA LUCIA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTO TOMAS', 'status' => true]);
        Ciudad::create(['nombre' => 'SOLEDAD', 'status' => true]);
        Ciudad::create(['nombre' => 'SUAN', 'status' => true]);
        Ciudad::create(['nombre' => 'TUBARA', 'status' => true]);
        Ciudad::create(['nombre' => 'USIACURI', 'status' => true]);
        Ciudad::create(['nombre' => 'Santa Fe de Bogotá', 'status' => true]);
        Ciudad::create(['nombre' => 'USAQUEN', 'status' => true]);
        Ciudad::create(['nombre' => 'CHAPINERO', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA FE', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN CRISTOBAL', 'status' => true]);
        Ciudad::create(['nombre' => 'USME', 'status' => true]);
        Ciudad::create(['nombre' => 'TUNJUELITO', 'status' => true]);
        Ciudad::create(['nombre' => 'BOSA', 'status' => true]);
        Ciudad::create(['nombre' => 'KENNEDY', 'status' => true]);
        Ciudad::create(['nombre' => 'FONTIBON', 'status' => true]);
        Ciudad::create(['nombre' => 'ENGATIVA', 'status' => true]);
        Ciudad::create(['nombre' => 'SUBA', 'status' => true]);
        Ciudad::create(['nombre' => 'BARRIOS UNIDOS', 'status' => true]);
        Ciudad::create(['nombre' => 'TEUSAQUILLO', 'status' => true]);
        Ciudad::create(['nombre' => 'MARTIRES', 'status' => true]);
        Ciudad::create(['nombre' => 'ANTONIO NARIÑO', 'status' => true]);
        Ciudad::create(['nombre' => 'PUENTE ARANDA', 'status' => true]);
        Ciudad::create(['nombre' => 'CANDELARIA', 'status' => true]);
        Ciudad::create(['nombre' => 'RAFAEL URIBE', 'status' => true]);
        Ciudad::create(['nombre' => '   CIUDAD BOLIVAR', 'status' => true]);
        Ciudad::create(['nombre' => 'SUMAPAZ', 'status' => true]);
        Ciudad::create(['nombre' =>'CARTAGENA (DISTRITO TURISTICO Y CULTURAL DE CARTAGENA)', 'status' => true]);
        Ciudad::create(['nombre' =>'ACHI', 'status' => true]);
        Ciudad::create(['nombre' => 'ALTOS DEL ROSARIO', 'status' => true]);
        Ciudad::create(['nombre' => 'ARENAL', 'status' => true]);
        Ciudad::create(['nombre' => 'ARJONA', 'status' => true]);
        Ciudad::create(['nombre' => 'ARROYOHONDO', 'status' => true]);
        Ciudad::create(['nombre' => 'BARRANCO DE LOBA', 'status' => true]);
        Ciudad::create(['nombre' => 'CALAMAR', 'status' => true]);
        Ciudad::create(['nombre' => 'CANTAGALLO', 'status' => true]);
        Ciudad::create(['nombre' => 'CICUCO', 'status' => true]);
        Ciudad::create(['nombre' => 'CORDOBA', 'status' => true]);
        Ciudad::create(['nombre' => 'CLEMENCIA', 'status' => true]);
        Ciudad::create(['nombre' => 'EL CARMEN DE BOLIVAR', 'status' => true]);
        Ciudad::create(['nombre' => 'EL GUAMO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL PEÑON', 'status' => true]);
        Ciudad::create(['nombre' => 'HATILLO DE LOBA', 'status' => true]);
        Ciudad::create(['nombre' => 'MAGANGUE', 'status' => true]);
        Ciudad::create(['nombre' => 'MAHATES', 'status' => true]);
        Ciudad::create(['nombre' => 'MARGARITA', 'status' => true]);
        Ciudad::create(['nombre' => 'MARIA LA BAJA', 'status' => true]);
        Ciudad::create(['nombre' => 'MONTECRISTO', 'status' => true]);
        Ciudad::create(['nombre' => 'MOMPOS', 'status' => true]);
        Ciudad::create(['nombre' => 'MORALES', 'status' => true]);
        Ciudad::create(['nombre' => 'PINILLOS', 'status' => true]);
        Ciudad::create(['nombre' => 'REGIDOR', 'status' => true]);
        Ciudad::create(['nombre' => 'RIO VIEJO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN CRISTOBAL', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ESTANISLAO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN FERNANDO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JACINTO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JACINTO DEL CAUCA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JUAN NEPOMUCENO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN MARTIN DE LOBA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN PABLO', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA CATALINA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA ROSA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA ROSA DEL SUR', 'status' => true]);
        Ciudad::create(['nombre' => 'SIMITI', 'status' => true]);
        Ciudad::create(['nombre' => 'SOPLAVIENTO', 'status' => true]);
        Ciudad::create(['nombre' => 'TALAIGUA NUEVO', 'status' => true]);
        Ciudad::create(['nombre' => 'TIQUISIO (PUERTO RICO)', 'status' => true]);
        Ciudad::create(['nombre' => 'TURBACO', 'status' => true]);
        Ciudad::create(['nombre' => 'TURBANA', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLANUEVA', 'status' => true]);
        Ciudad::create(['nombre' => 'ZAMBRANO', 'status' => true]);
        Ciudad::create(['nombre' => 'TUNJA', 'status' => true]);
        Ciudad::create(['nombre' => 'ALMEIDA', 'status' => true]);
        Ciudad::create(['nombre' => 'AQUITANIA', 'status' => true]);
        Ciudad::create(['nombre' => 'ARCABUCO', 'status' => true]);
        Ciudad::create(['nombre' => 'BELEN', 'status' => true]);
        Ciudad::create(['nombre' => 'BERBEO', 'status' => true]);
        Ciudad::create(['nombre' => 'BETEITIVA', 'status' => true]);
        Ciudad::create(['nombre' => 'BOAVITA', 'status' => true]);
        Ciudad::create(['nombre' => 'BOYACA', 'status' => true]);
        Ciudad::create(['nombre' => 'BRICEÑO', 'status' => true]);
        Ciudad::create(['nombre' => 'BUENAVISTA', 'status' => true]);
        Ciudad::create(['nombre' => 'BUSBANZA', 'status' => true]);
        Ciudad::create(['nombre' => 'CALDAS', 'status' => true]);
        Ciudad::create(['nombre' => 'CAMPOHERMOSO', 'status' => true]);
        Ciudad::create(['nombre' => 'CERINZA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHINAVITA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIQUINQUIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHISCAS', 'status' => true]);
        Ciudad::create(['nombre' => 'CHITA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHITARAQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIVATA', 'status' => true]);
        Ciudad::create(['nombre' => 'CIENEGA', 'status' => true]);
        Ciudad::create(['nombre' => 'COMBITA', 'status' => true]);
        Ciudad::create(['nombre' => 'COPER', 'status' => true]);
        Ciudad::create(['nombre' => 'CORRALES', 'status' => true]);
        Ciudad::create(['nombre' => 'COVARACHIA', 'status' => true]);
        Ciudad::create(['nombre' => 'CUBARA', 'status' => true]);
        Ciudad::create(['nombre' => 'CUCAITA', 'status' => true]);
        Ciudad::create(['nombre' => 'CUITIVA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIQUIZA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIVOR', 'status' => true]);
        Ciudad::create(['nombre' => 'DUITAMA', 'status' => true]);
        Ciudad::create(['nombre' => 'EL COCUY', 'status' => true]);
        Ciudad::create(['nombre' => 'EL ESPINO', 'status' => true]);
        Ciudad::create(['nombre' => 'FIRAVITOBA', 'status' => true]);
        Ciudad::create(['nombre' => 'FLORESTA', 'status' => true]);
        Ciudad::create(['nombre' => 'GACHANTIVA', 'status' => true]);
        Ciudad::create(['nombre' => 'GAMEZA', 'status' => true]);
        Ciudad::create(['nombre' => 'GARAGOA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUACAMAYAS', 'status' => true]);
        Ciudad::create(['nombre' => 'GUATEQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'GUAYATA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUICAN', 'status' => true]);
        Ciudad::create(['nombre' => 'IZA', 'status' => true]);
        Ciudad::create(['nombre' => 'JENESANO', 'status' => true]);
        Ciudad::create(['nombre' => 'JERICO', 'status' => true]);
        Ciudad::create(['nombre' => 'LABRANZAGRANDE', 'status' => true]);
        Ciudad::create(['nombre' => 'LA CAPILLA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA VICTORIA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA UVITA', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLA DE LEIVA', 'status' => true]);
        Ciudad::create(['nombre' => 'MACANAL', 'status' => true]);
        Ciudad::create(['nombre' => 'MARIPI', 'status' => true]);
        Ciudad::create(['nombre' => 'MIRAFLORES', 'status' => true]);
        Ciudad::create(['nombre' => 'MONGUA', 'status' => true]);
        Ciudad::create(['nombre' => 'MONGUI', 'status' => true]);
        Ciudad::create(['nombre' => 'MONIQUIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'MOTAVITA', 'status' => true]);
        Ciudad::create(['nombre' => 'MUZO', 'status' => true]);
        Ciudad::create(['nombre' => 'NOBSA', 'status' => true]);
        Ciudad::create(['nombre' => 'NUEVO COLON', 'status' => true]);
        Ciudad::create(['nombre' => 'OICATA', 'status' => true]);
        Ciudad::create(['nombre' => 'OTANCHE', 'status' => true]);
        Ciudad::create(['nombre' => 'PACHAVITA', 'status' => true]);
        Ciudad::create(['nombre' => 'PAEZ', 'status' => true]);
        Ciudad::create(['nombre' => 'PAIPA', 'status' => true]);
        Ciudad::create(['nombre' => 'PAJARITO', 'status' => true]);
        Ciudad::create(['nombre' => 'PANQUEBA', 'status' => true]);
        Ciudad::create(['nombre' => 'PAUNA', 'status' => true]);
        Ciudad::create(['nombre' => 'PAYA', 'status' => true]);
        Ciudad::create(['nombre' => 'PAZ DEL RIO', 'status' => true]);
        Ciudad::create(['nombre' => 'PESCA', 'status' => true]);
        Ciudad::create(['nombre' => 'PISBA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO BOYACA', 'status' => true]);
        Ciudad::create(['nombre' => 'QUIPAMA', 'status' => true]);
        Ciudad::create(['nombre' => 'RAMIRIQUI', 'status' => true]);
        Ciudad::create(['nombre' => 'RAQUIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'RONDON', 'status' => true]);
        Ciudad::create(['nombre' => 'SABOYA', 'status' => true]);
        Ciudad::create(['nombre' => 'SACHICA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAMACA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN EDUARDO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JOSE DE PARE', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN LUIS DE GACENO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN MATEO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN MIGUEL DE SEMA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN PABLO DE BORBUR', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTANA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA MARIA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA ROSA DE VITERBO', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA SOFIA', 'status' => true]);
        Ciudad::create(['nombre' => 'SATIVANORTE', 'status' => true]);
        Ciudad::create(['nombre' => 'SATIVASUR', 'status' => true]);
        Ciudad::create(['nombre' => 'SIACHOQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'SOATA', 'status' => true]);
        Ciudad::create(['nombre' => 'SOCOTA', 'status' => true]);
        Ciudad::create(['nombre' => 'SOCHA', 'status' => true]);
        Ciudad::create(['nombre' => 'SOGAMOSO', 'status' => true]);
        Ciudad::create(['nombre' => 'SOMONDOCO', 'status' => true]);
        Ciudad::create(['nombre' => 'SORA', 'status' => true]);
        Ciudad::create(['nombre' => 'SOTAQUIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'SORACA', 'status' => true]);
        Ciudad::create(['nombre' => 'SUSACON', 'status' => true]);
        Ciudad::create(['nombre' => 'SUTAMARCHAN', 'status' => true]);
        Ciudad::create(['nombre' => 'SUTATENZA', 'status' => true]);
        Ciudad::create(['nombre' => 'TASCO', 'status' => true]);
        Ciudad::create(['nombre' => 'TENZA', 'status' => true]);
        Ciudad::create(['nombre' => 'TIBANA', 'status' => true]);
        Ciudad::create(['nombre' => 'TIBASOSA', 'status' => true]);
        Ciudad::create(['nombre' => 'TINJACA', 'status' => true]);
        Ciudad::create(['nombre' => 'TIPACOQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'TOCA', 'status' => true]);
        Ciudad::create(['nombre' => 'TOGUI', 'status' => true]);
        Ciudad::create(['nombre' => 'TOPAGA', 'status' => true]);
        Ciudad::create(['nombre' => 'TOTA', 'status' => true]);
        Ciudad::create(['nombre' => 'TUNUNGUA', 'status' => true]);
        Ciudad::create(['nombre' => 'TURMEQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'TUTA', 'status' => true]);
        Ciudad::create(['nombre' => 'TUTASA', 'status' => true]);
        Ciudad::create(['nombre' => 'UMBITA', 'status' => true]);
        Ciudad::create(['nombre' => 'VENTAQUEMADA', 'status' => true]);
        Ciudad::create(['nombre' => 'VIRACACHA', 'status' => true]);
        Ciudad::create(['nombre' => 'ZETAQUIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'MANIZALES', 'status' => true]);
        Ciudad::create(['nombre' => 'AGUADAS', 'status' => true]);
        Ciudad::create(['nombre' => 'ANSERMA', 'status' => true]);
        Ciudad::create(['nombre' => 'ARANZAZU', 'status' => true]);
        Ciudad::create(['nombre' => 'BELALCAZAR', 'status' => true]);
        Ciudad::create(['nombre' => 'CHINCHINA', 'status' => true]);
        Ciudad::create(['nombre' => 'FILADELFIA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA DORADA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA MERCED', 'status' => true]);
        Ciudad::create(['nombre' => 'MANZANARES', 'status' => true]);
        Ciudad::create(['nombre' => 'MARMATO', 'status' => true]);
        Ciudad::create(['nombre' => 'MARQUETALIA', 'status' => true]);
        Ciudad::create(['nombre' => 'MARULANDA', 'status' => true]);
        Ciudad::create(['nombre' => 'NEIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'NORCASIA', 'status' => true]);
        Ciudad::create(['nombre' => 'PACORA', 'status' => true]);
        Ciudad::create(['nombre' => 'PALESTINA', 'status' => true]);
        Ciudad::create(['nombre' => 'PENSILVANIA', 'status' => true]);
        Ciudad::create(['nombre' => 'RIOSUCIO', 'status' => true]);
        Ciudad::create(['nombre' => 'RISARALDA', 'status' => true]);
        Ciudad::create(['nombre' => 'SALAMINA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAMANA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JOSE', 'status' => true]);
        Ciudad::create(['nombre' => 'SUPIA', 'status' => true]);
        Ciudad::create(['nombre' => 'VICTORIA', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLAMARIA', 'status' => true]);
        Ciudad::create(['nombre' => 'VITERBO', 'status' => true]);
        Ciudad::create(['nombre' => 'FLORENCIA', 'status' => true]);
        Ciudad::create(['nombre' => 'ALBANIA', 'status' => true]);
        Ciudad::create(['nombre' => 'BELEN DE LOS ANDAQUIES', 'status' => true]);
        Ciudad::create(['nombre' => 'CARTAGENA DEL CHAIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'CURILLO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL DONCELLO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL PAUJIL', 'status' => true]);
        Ciudad::create(['nombre' => 'LA MONTAÑITA', 'status' => true]);
        Ciudad::create(['nombre' => 'MILAN', 'status' => true]);
        Ciudad::create(['nombre' => 'MORELIA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO RICO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JOSE DE FRAGUA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN VICENTE DEL CAGUAN', 'status' => true]);
        Ciudad::create(['nombre' => 'SOLANO', 'status' => true]);
        Ciudad::create(['nombre' => 'SOLITA', 'status' => true]);
        Ciudad::create(['nombre' => 'VALPARAISO', 'status' => true]);
        Ciudad::create(['nombre' => 'POPAYAN', 'status' => true]);
        Ciudad::create(['nombre' => 'ALMAGUER', 'status' => true]);
        Ciudad::create(['nombre' => 'ARGELIA', 'status' => true]);
        Ciudad::create(['nombre' => 'BALBOA', 'status' => true]);
        Ciudad::create(['nombre' => 'BOLIVAR', 'status' => true]);
        Ciudad::create(['nombre' => 'BUENOS AIRES', 'status' => true]);
        Ciudad::create(['nombre' => 'CAJIBIO', 'status' => true]);
        Ciudad::create(['nombre' => 'CALDONO', 'status' => true]);
        Ciudad::create(['nombre' => 'CALOTO', 'status' => true]);
        Ciudad::create(['nombre' => 'CORINTO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL TAMBO', 'status' => true]);
        Ciudad::create(['nombre' => 'FLORENCIA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUAPI', 'status' => true]);
        Ciudad::create(['nombre' => 'INZA', 'status' => true]);
        Ciudad::create(['nombre' => 'JAMBALO', 'status' => true]);
        Ciudad::create(['nombre' => 'LA SIERRA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA VEGA', 'status' => true]);
        Ciudad::create(['nombre' => 'LOPEZ (MICAY)', 'status' => true]);
        Ciudad::create(['nombre' => 'MERCADERES', 'status' => true]);
        Ciudad::create(['nombre' => 'MIRANDA', 'status' => true]);
        Ciudad::create(['nombre' => 'MORALES', 'status' => true]);
        Ciudad::create(['nombre' => 'PADILLA', 'status' => true]);
        Ciudad::create(['nombre' => 'PAEZ (BELALCAZAR)', 'status' => true]);
        Ciudad::create(['nombre' => 'PATIA (EL BORDO)', 'status' => true]);
        Ciudad::create(['nombre' => 'PIAMONTE', 'status' => true]);
        Ciudad::create(['nombre' => 'PIENDAMO', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO TEJADA', 'status' => true]);
        Ciudad::create(['nombre' => 'PURACE (COCONUCO)', 'status' => true]);
        Ciudad::create(['nombre' => 'ROSAS', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN SEBASTIAN', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTANDER DE QUILICHAO', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA ROSA', 'status' => true]);
        Ciudad::create(['nombre' => 'SILVIA', 'status' => true]);
        Ciudad::create(['nombre' => 'SOTARA (PAISPAMBA)', 'status' => true]);
        Ciudad::create(['nombre' => 'SUAREZ', 'status' => true]);
        Ciudad::create(['nombre' => 'TIMBIO', 'status' => true]);
        Ciudad::create(['nombre' => 'TIMBIQUI', 'status' => true]);
        Ciudad::create(['nombre' => 'TORIBIO', 'status' => true]);
        Ciudad::create(['nombre' => 'TOTORO', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLARICA', 'status' => true]);
        Ciudad::create(['nombre' => 'VALLEDUPAR', 'status' => true]);
        Ciudad::create(['nombre' => 'AGUACHICA', 'status' => true]);
        Ciudad::create(['nombre' => 'AGUSTIN CODAZZI', 'status' => true]);
        Ciudad::create(['nombre' => 'ASTREA', 'status' => true]);
        Ciudad::create(['nombre' => 'BECERRIL', 'status' => true]);
        Ciudad::create(['nombre' => 'BOSCONIA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIMICHAGUA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIRIGUANA', 'status' => true]);
        Ciudad::create(['nombre' => 'CURUMANI', 'status' => true]);
        Ciudad::create(['nombre' => 'EL COPEY', 'status' => true]);
        Ciudad::create(['nombre' => 'EL PASO', 'status' => true]);
        Ciudad::create(['nombre' => 'GAMARRA', 'status' => true]);
        Ciudad::create(['nombre' => 'GONZALEZ', 'status' => true]);
        Ciudad::create(['nombre' => 'LA GLORIA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA JAGUA IBIRICO', 'status' => true]);
        Ciudad::create(['nombre' => 'MANAURE (BALCON DEL CESAR)', 'status' => true]);
        Ciudad::create(['nombre' => 'PAILITAS', 'status' => true]);
        Ciudad::create(['nombre' => 'PELAYA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUEBLO BELLO', 'status' => true]);
        Ciudad::create(['nombre' => 'RIO DE ORO', 'status' => true]);
        Ciudad::create(['nombre' => 'LA PAZ (ROBLES)', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ALBERTO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN DIEGO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN MARTIN', 'status' => true]);
        Ciudad::create(['nombre' => 'TAMALAMEQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'MONTERIA', 'status' => true]);
        Ciudad::create(['nombre' => 'AYAPEL', 'status' => true]);
        Ciudad::create(['nombre' => 'BUENAVISTA', 'status' => true]);
        Ciudad::create(['nombre' => 'CANALETE', 'status' => true]);
        Ciudad::create(['nombre' => 'CERETE', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHINU', 'status' => true]);
        Ciudad::create(['nombre' => 'CIENAGA DE ORO', 'status' => true]);
        Ciudad::create(['nombre' => 'COTORRA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA APARTADA', 'status' => true]);
        Ciudad::create(['nombre' => 'LORICA', 'status' => true]);
        Ciudad::create(['nombre' => 'LOS CORDOBAS', 'status' => true]);
        Ciudad::create(['nombre' => 'MOMIL', 'status' => true]);
        Ciudad::create(['nombre' => 'MONTELIBANO', 'status' => true]);
        Ciudad::create(['nombre' => 'MOÑITOS', 'status' => true]);
        Ciudad::create(['nombre' => 'PLANETA RICA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUEBLO NUEVO', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO ESCONDIDO', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO LIBERTADOR', 'status' => true]);
        Ciudad::create(['nombre' => 'PURISIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAHAGUN', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ANDRES SOTAVENTO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ANTERO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN BERNARDO DEL VIENTO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN CARLOS', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN PELAYO', 'status' => true]);
        Ciudad::create(['nombre' => 'TIERRALTA', 'status' => true]);
        Ciudad::create(['nombre' => 'VALENCIA', 'status' => true]);
        Ciudad::create(['nombre' => 'AGUA DE DIOS', 'status' => true]);
        Ciudad::create(['nombre' => 'ALBAN', 'status' => true]);
        Ciudad::create(['nombre' => 'ANAPOIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'ANOLAIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'ARBELAEZ', 'status' => true]);
        Ciudad::create(['nombre' => 'BELTRAN', 'status' => true]);
        Ciudad::create(['nombre' => 'BITUIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'BOJACA', 'status' => true]);
        Ciudad::create(['nombre' => 'CABRERA', 'status' => true]);
        Ciudad::create(['nombre' => 'CACHIPAY', 'status' => true]);
        Ciudad::create(['nombre' => 'CAJICA', 'status' => true]);
        Ciudad::create(['nombre' => 'CAPARRAPI', 'status' => true]);
        Ciudad::create(['nombre' => 'CAQUEZA', 'status' => true]);
        Ciudad::create(['nombre' => 'CARMEN DE CARUPA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHAGUANI', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIPAQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'CHOACHI', 'status' => true]);
        Ciudad::create(['nombre' => 'CHOCONTA', 'status' => true]);
        Ciudad::create(['nombre' => 'COGUA', 'status' => true]);
        Ciudad::create(['nombre' => 'COTA', 'status' => true]);
        Ciudad::create(['nombre' => 'CUCUNUBA', 'status' => true]);
        Ciudad::create(['nombre' => 'EL COLEGIO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL PEÑON', 'status' => true]);
        Ciudad::create(['nombre' => 'EL ROSAL', 'status' => true]);
        Ciudad::create(['nombre' => 'FACATATIVA', 'status' => true]);
        Ciudad::create(['nombre' => 'FOMEQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'FOSCA', 'status' => true]);
        Ciudad::create(['nombre' => 'FUNZA', 'status' => true]);
        Ciudad::create(['nombre' => 'FUQUENE', 'status' => true]);
        Ciudad::create(['nombre' => 'FUSAGASUGA', 'status' => true]);
        Ciudad::create(['nombre' => 'GACHALA', 'status' => true]);
        Ciudad::create(['nombre' => 'GACHANCIPA', 'status' => true]);
        Ciudad::create(['nombre' => 'GACHETA', 'status' => true]);
        Ciudad::create(['nombre' => 'GAMA', 'status' => true]);
        Ciudad::create(['nombre' => 'GIRARDOT', 'status' => true]);
        Ciudad::create(['nombre' => 'GRANADA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUACHETA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUADUAS', 'status' => true]);
        Ciudad::create(['nombre' => 'GUASCA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUATAQUI', 'status' => true]);
        Ciudad::create(['nombre' => 'GUATAVITA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUAYABAL DE SIQUIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUAYABETAL', 'status' => true]);
        Ciudad::create(['nombre' => 'GUTIERREZ', 'status' => true]);
        Ciudad::create(['nombre' => 'JERUSALEN', 'status' => true]);
        Ciudad::create(['nombre' => 'JUNIN', 'status' => true]);
        Ciudad::create(['nombre' => 'LA CALERA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA MESA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA PALMA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA PEÑA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA VEGA', 'status' => true]);
        Ciudad::create(['nombre' => 'LENGUAZAQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'MACHETA', 'status' => true]);
        Ciudad::create(['nombre' => 'MADRID', 'status' => true]);
        Ciudad::create(['nombre' => 'MANTA', 'status' => true]);
        Ciudad::create(['nombre' => 'MEDINA', 'status' => true]);
        Ciudad::create(['nombre' => 'MOSQUERA', 'status' => true]);
        Ciudad::create(['nombre' => 'NARIÑO', 'status' => true]);
        Ciudad::create(['nombre' => 'NEMOCON', 'status' => true]);
        Ciudad::create(['nombre' => 'NILO', 'status' => true]);
        Ciudad::create(['nombre' => 'NIMAIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'NOCAIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'VENECIA (OSPINA PEREZ)', 'status' => true]);
        Ciudad::create(['nombre' => 'PACHO', 'status' => true]);
        Ciudad::create(['nombre' => 'PAIME', 'status' => true]);
        Ciudad::create(['nombre' => 'PANDI', 'status' => true]);
        Ciudad::create(['nombre' => 'PARATEBUENO', 'status' => true]);
        Ciudad::create(['nombre' => 'PASCA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO SALGAR', 'status' => true]);
        Ciudad::create(['nombre' => 'PULI', 'status' => true]);
        Ciudad::create(['nombre' => 'QUEBRADANEGRA', 'status' => true]);
        Ciudad::create(['nombre' => 'QUETAME', 'status' => true]);
        Ciudad::create(['nombre' => 'QUIPILE', 'status' => true]);
        Ciudad::create(['nombre' => 'APULO (RAFAEL REYES)', 'status' => true]);
        Ciudad::create(['nombre' => 'RICAURTE', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ANTONIO DEL TEQUENDAMA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN BERNARDO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN CAYETANO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN FRANCISCO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JUAN DE RIOSECO', 'status' => true]);
        Ciudad::create(['nombre' => 'SASAIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'SESQUILE', 'status' => true]);
        Ciudad::create(['nombre' => 'SIBATE', 'status' => true]);
        Ciudad::create(['nombre' => 'SILVANIA', 'status' => true]);
        Ciudad::create(['nombre' => 'SIMIJACA', 'status' => true]);
        Ciudad::create(['nombre' => 'SOACHA', 'status' => true]);
        Ciudad::create(['nombre' => 'SOPO', 'status' => true]);
        Ciudad::create(['nombre' => 'SUBACHOQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'SUESCA', 'status' => true]);
        Ciudad::create(['nombre' => 'SUPATA', 'status' => true]);
        Ciudad::create(['nombre' => 'SUSA', 'status' => true]);
        Ciudad::create(['nombre' => 'SUTATAUSA', 'status' => true]);
        Ciudad::create(['nombre' => 'TABIO', 'status' => true]);
        Ciudad::create(['nombre' => 'TAUSA', 'status' => true]);
        Ciudad::create(['nombre' => 'TENA', 'status' => true]);
        Ciudad::create(['nombre' => 'TENJO', 'status' => true]);
        Ciudad::create(['nombre' => 'TIBACUY', 'status' => true]);
        Ciudad::create(['nombre' => 'TIBIRITA', 'status' => true]);
        Ciudad::create(['nombre' => 'TOCAIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'TOCANCIPA', 'status' => true]);
        Ciudad::create(['nombre' => 'TOPAIPI', 'status' => true]);
        Ciudad::create(['nombre' => 'UBALA', 'status' => true]);
        Ciudad::create(['nombre' => 'UBAQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'UBATE', 'status' => true]);
        Ciudad::create(['nombre' => 'UNE', 'status' => true]);
        Ciudad::create(['nombre' => 'UTICA', 'status' => true]);
        Ciudad::create(['nombre' => 'VERGARA', 'status' => true]);
        Ciudad::create(['nombre' => 'VIANI', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLAGOMEZ', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLAPINZON', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLETA', 'status' => true]);
        Ciudad::create(['nombre' => 'VIOTA', 'status' => true]);
        Ciudad::create(['nombre' => 'YACOPI', 'status' => true]);
        Ciudad::create(['nombre' => 'ZIPACON', 'status' => true]);
        Ciudad::create(['nombre' => 'ZIPAQUIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'QUIBDO (SAN FRANCISCO DE QUIBDO)', 'status' => true]);
        Ciudad::create(['nombre' => 'ACANDI', 'status' => true]);
        Ciudad::create(['nombre' => 'ALTO BAUDO (PIE DE PATO)', 'status' => true]);
        Ciudad::create(['nombre' => 'ATRATO', 'status' => true]);
        Ciudad::create(['nombre' => 'BAGADO', 'status' => true]);
        Ciudad::create(['nombre' => 'BAHIA SOLANO (MUTIS)', 'status' => true]);
        Ciudad::create(['nombre' => 'BAJO BAUDO (PIZARRO)', 'status' => true]);
        Ciudad::create(['nombre' => 'BOJAYA (BELLAVISTA)', 'status' => true]);
        Ciudad::create(['nombre' => 'CANTON DE SAN PABLO (MANAGRU)', 'status' => true]);
        Ciudad::create(['nombre' => 'CONDOTO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL CARMEN DE ATRATO', 'status' => true]);
        Ciudad::create(['nombre' => 'LITORAL DEL BAJO SAN JUAN (SANTA GENOVEVA DE DOCORDO)', 'status' => true]);
        Ciudad::create(['nombre' => 'ISTMINA', 'status' => true]);
        Ciudad::create(['nombre' => 'JURADO', 'status' => true]);
        Ciudad::create(['nombre' => 'LLORO', 'status' => true]);
        Ciudad::create(['nombre' => 'MEDIO ATRATO', 'status' => true]);
        Ciudad::create(['nombre' => 'MEDIO BAUDO', 'status' => true]);
        Ciudad::create(['nombre' => 'NOVITA', 'status' => true]);
        Ciudad::create(['nombre' => 'NUQUI', 'status' => true]);
        Ciudad::create(['nombre' => 'RIOQUITO', 'status' => true]);
        Ciudad::create(['nombre' => 'RIOSUCIO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JOSE DEL PALMAR', 'status' => true]);
        Ciudad::create(['nombre' => 'SIPI', 'status' => true]);
        Ciudad::create(['nombre' => 'TADO', 'status' => true]);
        Ciudad::create(['nombre' => 'UNGUIA', 'status' => true]);
        Ciudad::create(['nombre' => 'UNION PANAMERICANA', 'status' => true]);
        Ciudad::create(['nombre' => 'NEIVA', 'status' => true]);
        Ciudad::create(['nombre' => 'ACEVEDO', 'status' => true]);
        Ciudad::create(['nombre' =>'AGRADO', 'status' => true]);
        Ciudad::create(['nombre' =>'AIPE', 'status' => true]);
        Ciudad::create(['nombre' =>'ALGECIRAS', 'status' => true]);
        Ciudad::create(['nombre' =>'ALTAMIRA', 'status' => true]);
        Ciudad::create(['nombre' =>'BARAYA', 'status' => true]);
        Ciudad::create(['nombre' => 'CAMPOALEGRE', 'status' => true]);
        Ciudad::create(['nombre' => 'COLOMBIA', 'status' => true]);
        Ciudad::create(['nombre' => 'ELIAS', 'status' => true]);
        Ciudad::create(['nombre' => 'GARZON', 'status' => true]);
        Ciudad::create(['nombre' => 'GIGANTE', 'status' => true]);
        Ciudad::create(['nombre' => 'GUADALUPE', 'status' => true]);
        Ciudad::create(['nombre' => 'HOBO', 'status' => true]);
        Ciudad::create(['nombre' => 'IQUIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'ISNOS (SAN JOSE DE ISNOS)', 'status' => true]);
        Ciudad::create(['nombre' => 'LA ARGENTINA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA PLATA', 'status' => true]);
        Ciudad::create(['nombre' => 'NATAGA', 'status' => true]);
        Ciudad::create(['nombre' => 'OPORAPA', 'status' => true]);
        Ciudad::create(['nombre' => 'PAICOL', 'status' => true]);
        Ciudad::create(['nombre' => 'PALERMO', 'status' => true]);
        Ciudad::create(['nombre' => 'PALESTINA', 'status' => true]);
        Ciudad::create(['nombre' => 'PITAL', 'status' => true]);
        Ciudad::create(['nombre' => 'PITALITO', 'status' => true]);
        Ciudad::create(['nombre' => 'RIVERA', 'status' => true]);
        Ciudad::create(['nombre' => 'SALADOBLANCO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN AGUSTIN', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA MARIA', 'status' => true]);
        Ciudad::create(['nombre' => 'SUAZA', 'status' => true]);
        Ciudad::create(['nombre' => 'TARQUI', 'status' => true]);
        Ciudad::create(['nombre' => 'TESALIA', 'status' => true]);
        Ciudad::create(['nombre' => 'TELLO', 'status' => true]);
        Ciudad::create(['nombre' => 'TERUEL', 'status' => true]);
        Ciudad::create(['nombre' => 'TIMANA', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLAVIEJA', 'status' => true]);
        Ciudad::create(['nombre' => 'YAGUARA', 'status' => true]);
        Ciudad::create(['nombre' => 'RIOHACHA', 'status' => true]);
        Ciudad::create(['nombre' => 'BARRANCAS', 'status' => true]);
        Ciudad::create(['nombre' => 'DIBULLA', 'status' => true]);
        Ciudad::create(['nombre' => 'DISTRACCION', 'status' => true]);
        Ciudad::create(['nombre' => 'EL MOLINO', 'status' => true]);
        Ciudad::create(['nombre' => 'FONSECA', 'status' => true]);
        Ciudad::create(['nombre' => 'HATONUEVO', 'status' => true]);
        Ciudad::create(['nombre' => 'LA JAGUA DEL PILAR', 'status' => true]);
        Ciudad::create(['nombre' => 'MAICAO', 'status' => true]);
        Ciudad::create(['nombre' => 'MANAURE', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JUAN DEL CESAR', 'status' => true]);
        Ciudad::create(['nombre' => 'URIBIA', 'status' => true]);
        Ciudad::create(['nombre' => 'URUMITA', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLANUEVA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA MARTA (DISTRITO TURISTICO CULTURAL E HISTORICO DE SANTA MARTA)', 'status' => true]);
        Ciudad::create(['nombre' =>'ALGARROBO', 'status' => true]);
        Ciudad::create(['nombre' =>'ARACATACA', 'status' => true]);
        Ciudad::create(['nombre' =>'ARIGUANI (EL DIFICIL)', 'status' => true]);
        Ciudad::create(['nombre' => 'CERRO SAN ANTONIO', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIVOLO', 'status' => true]);
        Ciudad::create(['nombre' => 'CIENAGA', 'status' => true]);
        Ciudad::create(['nombre' => 'CONCORDIA', 'status' => true]);
        Ciudad::create(['nombre' => 'EL BANCO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL PIÑON', 'status' => true]);
        Ciudad::create(['nombre' => 'EL RETEN', 'status' => true]);
        Ciudad::create(['nombre' => 'FUNDACION', 'status' => true]);
        Ciudad::create(['nombre' => 'GUAMAL', 'status' => true]);
        Ciudad::create(['nombre' => 'PEDRAZA', 'status' => true]);
        Ciudad::create(['nombre' => 'PIJIÑO DEL CARMEN (PIJIÑO)', 'status' => true]);
        Ciudad::create(['nombre' => 'PIVIJAY', 'status' => true]);
        Ciudad::create(['nombre' => 'PLATO', 'status' => true]);
        Ciudad::create(['nombre' => 'PUEBLOVIEJO', 'status' => true]);
        Ciudad::create(['nombre' => 'REMOLINO', 'status' => true]);
        Ciudad::create(['nombre' => 'SABANAS DE SAN ANGEL', 'status' => true]);
        Ciudad::create(['nombre' => 'SALAMINA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN SEBASTIAN DE BUENAVISTA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ZENON', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA ANA', 'status' => true]);
        Ciudad::create(['nombre' => 'SITIONUEVO', 'status' => true]);
        Ciudad::create(['nombre' => 'TENERIFE', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLAVICENCIO', 'status' => true]);
        Ciudad::create(['nombre' => 'ACACIAS', 'status' => true]);
        Ciudad::create(['nombre' => 'BARRANCA DE UPIA', 'status' => true]);
        Ciudad::create(['nombre' => 'CABUYARO', 'status' => true]);
        Ciudad::create(['nombre' => 'CASTILLA LA NUEVA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN LUIS DE CUBARRAL', 'status' => true]);
        Ciudad::create(['nombre' => 'CUMARAL', 'status' => true]);
        Ciudad::create(['nombre' => 'EL CALVARIO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL CASTILLO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL DORADO', 'status' => true]);
        Ciudad::create(['nombre' => 'FUENTE DE ORO', 'status' => true]);
        Ciudad::create(['nombre' => 'GRANADA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUAMAL', 'status' => true]);
        Ciudad::create(['nombre' => 'MAPIRIPAN', 'status' => true]);
        Ciudad::create(['nombre' => 'MESETAS', 'status' => true]);
        Ciudad::create(['nombre' => 'LA MACARENA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA URIBE', 'status' => true]);
        Ciudad::create(['nombre' => 'LEJANIAS', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO CONCORDIA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO GAITAN', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO LOPEZ', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO LLERAS', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO RICO', 'status' => true]);
        Ciudad::create(['nombre' => 'RESTREPO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN CARLOS DE GUAROA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JUAN DE ARAMA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JUANITO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN MARTIN', 'status' => true]);
        Ciudad::create(['nombre' => 'VISTAHERMOSA', 'status' => true]);
        Ciudad::create(['nombre' => 'PASTO (SAN JUAN DE PASTO)', 'status' => true]);
        Ciudad::create(['nombre' => 'ALBAN (SAN JOSE)', 'status' => true]);
        Ciudad::create(['nombre' =>'ALDANA', 'status' => true]);
        Ciudad::create(['nombre' =>'ANCUYA', 'status' => true]);
        Ciudad::create(['nombre' =>'ARBOLEDA (BERRUECOS)', 'status' => true]);
        Ciudad::create(['nombre' =>'BARBACOAS', 'status' => true]);
        Ciudad::create(['nombre' =>'BELEN', 'status' => true]);
        Ciudad::create(['nombre' => 'BUESACO', 'status' => true]);
        Ciudad::create(['nombre' => 'COLON (GENOVA)', 'status' => true]);
        Ciudad::create(['nombre' => 'CONSACA', 'status' => true]);
        Ciudad::create(['nombre' => 'CONTADERO', 'status' => true]);
        Ciudad::create(['nombre' => 'CORDOBA', 'status' => true]);
        Ciudad::create(['nombre' => 'CUASPUD (CARLOSAMA)', 'status' => true]);
        Ciudad::create(['nombre' => 'CUMBAL', 'status' => true]);
        Ciudad::create(['nombre' => 'CUMBITARA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHACHAGUI', 'status' => true]);
        Ciudad::create(['nombre' => 'EL CHARCO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL PEÑOL', 'status' => true]);
        Ciudad::create(['nombre' => 'EL ROSARIO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL TABLON', 'status' => true]);
        Ciudad::create(['nombre' => 'EL TAMBO', 'status' => true]);
        Ciudad::create(['nombre' => 'FUNES', 'status' => true]);
        Ciudad::create(['nombre' => 'GUACHUCAL', 'status' => true]);
        Ciudad::create(['nombre' => 'GUAITARILLA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUALMATAN', 'status' => true]);
        Ciudad::create(['nombre' => 'ILES', 'status' => true]);
        Ciudad::create(['nombre' => 'IMUES', 'status' => true]);
        Ciudad::create(['nombre' => 'IPIALES', 'status' => true]);
        Ciudad::create(['nombre' => 'LA CRUZ', 'status' => true]);
        Ciudad::create(['nombre' => 'LA FLORIDA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA LLANADA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA TOLA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA UNION', 'status' => true]);
        Ciudad::create(['nombre' => 'LEIVA', 'status' => true]);
        Ciudad::create(['nombre' => 'LINARES', 'status' => true]);
        Ciudad::create(['nombre' => 'LOS ANDES (SOTOMAYOR)', 'status' => true]);
        Ciudad::create(['nombre' => 'MAGUI (PAYAN)', 'status' => true]);
        Ciudad::create(['nombre' => 'MALLAMA (PIEDRANCHA)', 'status' => true]);
        Ciudad::create(['nombre' => 'MOSQUERA', 'status' => true]);
        Ciudad::create(['nombre' => 'OLAYA HERRERA (BOCAS DE SATINGA)', 'status' => true]);
        Ciudad::create(['nombre' => 'OSPINA', 'status' => true]);
        Ciudad::create(['nombre' => 'FRANCISCO PIZARRO (SALAHONDA)', 'status' => true]);
        Ciudad::create(['nombre' => 'POLICARPA', 'status' => true]);
        Ciudad::create(['nombre' => 'POTOSI', 'status' => true]);
        Ciudad::create(['nombre' => 'PROVIDENCIA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERRES', 'status' => true]);
        Ciudad::create(['nombre' => 'PUPIALES', 'status' => true]);
        Ciudad::create(['nombre' => 'RICAURTE', 'status' => true]);
        Ciudad::create(['nombre' => 'ROBERTO PAYAN (SAN JOSE)', 'status' => true]);
        Ciudad::create(['nombre' => 'SAMANIEGO', 'status' => true]);
        Ciudad::create(['nombre' => 'SANDONA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN BERNARDO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN LORENZO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN PABLO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN PEDRO DE CARTAGO', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA BARBARA (ISCUANDE)', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA CRUZ (GUACHAVES)', 'status' => true]);
        Ciudad::create(['nombre' => 'SAPUYES', 'status' => true]);
        Ciudad::create(['nombre' => 'TAMINANGO', 'status' => true]);
        Ciudad::create(['nombre' => 'TANGUA', 'status' => true]);
        Ciudad::create(['nombre' => 'TUMACO', 'status' => true]);
        Ciudad::create(['nombre' => 'TUQUERRES', 'status' => true]);
        Ciudad::create(['nombre' => 'YACUANQUER', 'status' => true]);
        Ciudad::create(['nombre' => 'CUCUTA', 'status' => true]);
        Ciudad::create(['nombre' => 'ABREGO', 'status' => true]);
        Ciudad::create(['nombre' =>'ARBOLEDAS', 'status' => true]);
        Ciudad::create(['nombre' =>'BOCHALEMA', 'status' => true]);
        Ciudad::create(['nombre' => 'BUCARASICA', 'status' => true]);
        Ciudad::create(['nombre' => 'CACOTA', 'status' => true]);
        Ciudad::create(['nombre' => 'CACHIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHINACOTA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHITAGA', 'status' => true]);
        Ciudad::create(['nombre' => 'CONVENCION', 'status' => true]);
        Ciudad::create(['nombre' => 'CUCUTILLA', 'status' => true]);
        Ciudad::create(['nombre' => 'DURANIA', 'status' => true]);
        Ciudad::create(['nombre' => 'EL CARMEN', 'status' => true]);
        Ciudad::create(['nombre' => 'EL TARRA', 'status' => true]);
        Ciudad::create(['nombre' => 'EL ZULIA', 'status' => true]);
        Ciudad::create(['nombre' => 'GRAMALOTE', 'status' => true]);
        Ciudad::create(['nombre' => 'HACARI', 'status' => true]);
        Ciudad::create(['nombre' => 'HERRAN', 'status' => true]);
        Ciudad::create(['nombre' => 'LABATECA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA ESPERANZA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA PLAYA', 'status' => true]);
        Ciudad::create(['nombre' => 'LOS PATIOS', 'status' => true]);
        Ciudad::create(['nombre' => 'LOURDES', 'status' => true]);
        Ciudad::create(['nombre' => 'MUTISCUA', 'status' => true]);
        Ciudad::create(['nombre' => 'OCAÑA', 'status' => true]);
        Ciudad::create(['nombre' => 'PAMPLONA', 'status' => true]);
        Ciudad::create(['nombre' => 'PAMPLONITA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO SANTANDER', 'status' => true]);
        Ciudad::create(['nombre' => 'RAGONVALIA', 'status' => true]);
        Ciudad::create(['nombre' => 'SALAZAR', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN CALIXTO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN CAYETANO', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTIAGO', 'status' => true]);
        Ciudad::create(['nombre' => 'SARDINATA', 'status' => true]);
        Ciudad::create(['nombre' => 'SILOS', 'status' => true]);
        Ciudad::create(['nombre' => 'TEORAMA', 'status' => true]);
        Ciudad::create(['nombre' => 'TIBU', 'status' => true]);
        Ciudad::create(['nombre' => 'TOLEDO', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLACARO', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLA DEL ROSARIO', 'status' => true]);
        Ciudad::create(['nombre' => 'ARMENIA', 'status' => true]);
        Ciudad::create(['nombre' => 'BUENAVISTA', 'status' => true]);
        Ciudad::create(['nombre' => 'CALARCA', 'status' => true]);
        Ciudad::create(['nombre' => 'CIRCASIA', 'status' => true]);
        Ciudad::create(['nombre' => 'CORDOBA', 'status' => true]);
        Ciudad::create(['nombre' => 'FILANDIA', 'status' => true]);
        Ciudad::create(['nombre' => 'GENOVA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA TEBAIDA', 'status' => true]);
        Ciudad::create(['nombre' => 'MONTENEGRO', 'status' => true]);
        Ciudad::create(['nombre' => 'PIJAO', 'status' => true]);
        Ciudad::create(['nombre' => 'QUIMBAYA', 'status' => true]);
        Ciudad::create(['nombre' => 'SALENTO', 'status' => true]);
        Ciudad::create(['nombre' => 'PEREIRA' , 'status' => true]);
        Ciudad::create(['nombre' =>'APIA', 'status' => true]);
        Ciudad::create(['nombre' =>'BALBOA', 'status' => true]);
        Ciudad::create(['nombre' =>'BELEN DE UMBRIA', 'status' => true]);
        Ciudad::create(['nombre' => 'DOS QUEBRADAS', 'status' => true]);
        Ciudad::create(['nombre' => 'GUATICA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA CELIA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA VIRGINIA', 'status' => true]);
        Ciudad::create(['nombre' => 'MARSELLA', 'status' => true]);
        Ciudad::create(['nombre' => 'MISTRATO', 'status' => true]);
        Ciudad::create(['nombre' => 'PUEBLO RICO', 'status' => true]);
        Ciudad::create(['nombre' => 'QUINCHIA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA ROSA DE CABAL', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTUARIO', 'status' => true]);
        Ciudad::create(['nombre' => 'BUCARAMANGA', 'status' => true]);
        Ciudad::create(['nombre' =>'AGUADA', 'status' => true]);
        Ciudad::create(['nombre' =>'ALBANIA', 'status' => true]);
        Ciudad::create(['nombre' =>'ARATOCA', 'status' => true]);
        Ciudad::create(['nombre' =>'BARBOSA', 'status' => true]);
        Ciudad::create(['nombre' =>'BARICHARA', 'status' => true]);
        Ciudad::create(['nombre' =>'BARRANCABERMEJA', 'status' => true]);
        Ciudad::create(['nombre' =>'BETULIA', 'status' => true]);
        Ciudad::create(['nombre' => 'BOLIVAR', 'status' => true]);
        Ciudad::create(['nombre' => 'CABRERA', 'status' => true]);
        Ciudad::create(['nombre' => 'CALIFORNIA', 'status' => true]);
        Ciudad::create(['nombre' => 'CAPITANEJO', 'status' => true]);
        Ciudad::create(['nombre' => 'CARCASI', 'status' => true]);
        Ciudad::create(['nombre' => 'CEPITA', 'status' => true]);
        Ciudad::create(['nombre' => 'CERRITO', 'status' => true]);
        Ciudad::create(['nombre' => 'CHARALA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHARTA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHIPATA', 'status' => true]);
        Ciudad::create(['nombre' => 'CIMITARRA', 'status' => true]);
        Ciudad::create(['nombre' => 'CONCEPCION', 'status' => true]);
        Ciudad::create(['nombre' => 'CONFINES', 'status' => true]);
        Ciudad::create(['nombre' => 'CONTRATACION', 'status' => true]);
        Ciudad::create(['nombre' => 'COROMORO', 'status' => true]);
        Ciudad::create(['nombre' => 'CURITI', 'status' => true]);
        Ciudad::create(['nombre' => 'EL CARMEN DE CHUCURY', 'status' => true]);
        Ciudad::create(['nombre' => 'EL GUACAMAYO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL PEÑON', 'status' => true]);
        Ciudad::create(['nombre' => 'EL PLAYON', 'status' => true]);
        Ciudad::create(['nombre' => 'ENCINO', 'status' => true]);
        Ciudad::create(['nombre' => 'ENCISO', 'status' => true]);
        Ciudad::create(['nombre' => 'FLORIAN', 'status' => true]);
        Ciudad::create(['nombre' => 'FLORIDABLANCA', 'status' => true]);
        Ciudad::create(['nombre' => 'GALAN', 'status' => true]);
        Ciudad::create(['nombre' => 'GAMBITA', 'status' => true]);
        Ciudad::create(['nombre' => 'GIRON', 'status' => true]);
        Ciudad::create(['nombre' => 'GUACA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUADALUPE', 'status' => true]);
        Ciudad::create(['nombre' => 'GUAPOTA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUAVATA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUEPSA', 'status' => true]);
        Ciudad::create(['nombre' => 'HATO', 'status' => true]);
        Ciudad::create(['nombre' => 'JESUS MARIA', 'status' => true]);
        Ciudad::create(['nombre' => 'JORDAN', 'status' => true]);
        Ciudad::create(['nombre' => 'LA BELLEZA', 'status' => true]);
        Ciudad::create(['nombre' => 'LANDAZURI', 'status' => true]);
        Ciudad::create(['nombre' => 'LA PAZ', 'status' => true]);
        Ciudad::create(['nombre' => 'LEBRIJA', 'status' => true]);
        Ciudad::create(['nombre' => 'LOS SANTOS', 'status' => true]);
        Ciudad::create(['nombre' => 'MACARAVITA', 'status' => true]);
        Ciudad::create(['nombre' => 'MALAGA', 'status' => true]);
        Ciudad::create(['nombre' => 'MATANZA', 'status' => true]);
        Ciudad::create(['nombre' => 'MOGOTES', 'status' => true]);
        Ciudad::create(['nombre' => 'MOLAGAVITA', 'status' => true]);
        Ciudad::create(['nombre' => 'OCAMONTE', 'status' => true]);
        Ciudad::create(['nombre' => 'OIBA', 'status' => true]);
        Ciudad::create(['nombre' => 'ONZAGA', 'status' => true]);
        Ciudad::create(['nombre' => 'PALMAR', 'status' => true]);
        Ciudad::create(['nombre' => 'PALMAS DEL SOCORRO', 'status' => true]);
        Ciudad::create(['nombre' => 'PARAMO', 'status' => true]);
        Ciudad::create(['nombre' => 'PIEDECUESTA', 'status' => true]);
        Ciudad::create(['nombre' => 'PINCHOTE', 'status' => true]);
        Ciudad::create(['nombre' => 'PUENTE NACIONAL', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO PARRA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO WILCHES', 'status' => true]);
        Ciudad::create(['nombre' => 'RIONEGRO', 'status' => true]);
        Ciudad::create(['nombre' => 'SABANA DE TORRES', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ANDRES', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN BENITO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN GIL', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JOAQUIN', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JOSE DE MIRANDA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN MIGUEL', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN VICENTE DE CHUCURI', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA BARBARA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA HELENA DEL OPON', 'status' => true]);
        Ciudad::create(['nombre' => 'SIMACOTA', 'status' => true]);
        Ciudad::create(['nombre' => 'SOCORRO', 'status' => true]);
        Ciudad::create(['nombre' => 'SUAITA', 'status' => true]);
        Ciudad::create(['nombre' => 'SUCRE', 'status' => true]);
        Ciudad::create(['nombre' => 'SURATA', 'status' => true]);
        Ciudad::create(['nombre' => 'TONA', 'status' => true]);
        Ciudad::create(['nombre' => 'VALLE SAN JOSE', 'status' => true]);
        Ciudad::create(['nombre' => 'VELEZ', 'status' => true]);
        Ciudad::create(['nombre' => 'VETAS', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLANUEVA', 'status' => true]);
        Ciudad::create(['nombre' => 'ZAPATOCA', 'status' => true]);
        Ciudad::create(['nombre' => 'SINCELEJO', 'status' => true]);
        Ciudad::create(['nombre' => 'BUENAVISTA', 'status' => true]);
        Ciudad::create(['nombre' => 'CAIMITO', 'status' => true]);
        Ciudad::create(['nombre' => 'COLOSO (RICAURTE)', 'status' => true]);
        Ciudad::create(['nombre' => 'COROZAL', 'status' => true]);
        Ciudad::create(['nombre' => 'CHALAN', 'status' => true]);
        Ciudad::create(['nombre' => 'GALERAS (NUEVA GRANADA)', 'status' => true]);
        Ciudad::create(['nombre' => 'GUARANDA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA UNION', 'status' => true]);
        Ciudad::create(['nombre' => 'LOS PALMITOS', 'status' => true]);
        Ciudad::create(['nombre' => 'MAJAGUAL', 'status' => true]);
        Ciudad::create(['nombre' => 'MORROA', 'status' => true]);
        Ciudad::create(['nombre' => 'OVEJAS', 'status' => true]);
        Ciudad::create(['nombre' => 'PALMITO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAMPUES', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN BENITO ABAD', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JUAN DE BETULIA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN MARCOS', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ONOFRE', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN PEDRO', 'status' => true]);
        Ciudad::create(['nombre' => 'SINCE', 'status' => true]);
        Ciudad::create(['nombre' => 'SUCRE', 'status' => true]);
        Ciudad::create(['nombre' => 'TOLU', 'status' => true]);
        Ciudad::create(['nombre' => 'TOLUVIEJO', 'status' => true]);
        Ciudad::create(['nombre' => 'IBAGUE', 'status' => true]);
        Ciudad::create(['nombre' =>'ALPUJARRA', 'status' => true]);
        Ciudad::create(['nombre' =>'ALVARADO', 'status' => true]);
        Ciudad::create(['nombre' =>'AMBALEMA', 'status' => true]);
        Ciudad::create(['nombre' =>'ANZOATEGUI', 'status' => true]);
        Ciudad::create(['nombre' =>'ARMERO (GUAYABAL)', 'status' => true]);
        Ciudad::create(['nombre' =>'ATACO', 'status' => true]);
        Ciudad::create(['nombre' => 'CAJAMARCA', 'status' => true]);
        Ciudad::create(['nombre' => 'CARMEN APICALA', 'status' => true]);
        Ciudad::create(['nombre' => 'CASABIANCA', 'status' => true]);
        Ciudad::create(['nombre' => 'CHAPARRAL', 'status' => true]);
        Ciudad::create(['nombre' => 'COELLO', 'status' => true]);
        Ciudad::create(['nombre' => 'COYAIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'CUNDAY', 'status' => true]);
        Ciudad::create(['nombre' => 'DOLORES', 'status' => true]);
        Ciudad::create(['nombre' => 'ESPINAL', 'status' => true]);
        Ciudad::create(['nombre' => 'FALAN', 'status' => true]);
        Ciudad::create(['nombre' => 'FLANDES', 'status' => true]);
        Ciudad::create(['nombre' => 'FRESNO', 'status' => true]);
        Ciudad::create(['nombre' => 'GUAMO', 'status' => true]);
        Ciudad::create(['nombre' => 'HERVEO', 'status' => true]);
        Ciudad::create(['nombre' => 'HONDA', 'status' => true]);
        Ciudad::create(['nombre' => 'ICONONZO', 'status' => true]);
        Ciudad::create(['nombre' => 'LERIDA', 'status' => true]);
        Ciudad::create(['nombre' => 'LIBANO', 'status' => true]);
        Ciudad::create(['nombre' => 'MARIQUITA', 'status' => true]);
        Ciudad::create(['nombre' => 'MELGAR', 'status' => true]);
        Ciudad::create(['nombre' => 'MURILLO', 'status' => true]);
        Ciudad::create(['nombre' => 'NATAGAIMA', 'status' => true]);
        Ciudad::create(['nombre' => 'ORTEGA', 'status' => true]);
        Ciudad::create(['nombre' => 'PALOCABILDO', 'status' => true]);
        Ciudad::create(['nombre' => 'PIEDRAS', 'status' => true]);
        Ciudad::create(['nombre' => 'PLANADAS', 'status' => true]);
        Ciudad::create(['nombre' => 'PRADO', 'status' => true]);
        Ciudad::create(['nombre' => 'PURIFICACION', 'status' => true]);
        Ciudad::create(['nombre' => 'RIOBLANCO', 'status' => true]);
        Ciudad::create(['nombre' => 'RONCESVALLES', 'status' => true]);
        Ciudad::create(['nombre' => 'ROVIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'SALDAÑA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ANTONIO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN LUIS', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA ISABEL', 'status' => true]);
        Ciudad::create(['nombre' => 'SUAREZ', 'status' => true]);
        Ciudad::create(['nombre' => 'VALLE DE SAN JUAN', 'status' => true]);
        Ciudad::create(['nombre' => 'VENADILLO', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLAHERMOSA', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLARRICA', 'status' => true]);
        Ciudad::create(['nombre' => 'CALI (SANTIAGO DE CALI)', 'status' => true]);
        Ciudad::create(['nombre' =>'ALCALA', 'status' => true]);
        Ciudad::create(['nombre' =>'ANDALUCIA', 'status' => true]);
        Ciudad::create(['nombre' =>'ANSERMANUEVO', 'status' => true]);
        Ciudad::create(['nombre' =>'ARGELIA', 'status' => true]);
        Ciudad::create(['nombre' => 'BOLIVAR', 'status' => true]);
        Ciudad::create(['nombre' => 'BUENAVENTURA', 'status' => true]);
        Ciudad::create(['nombre' => 'BUGA', 'status' => true]);
        Ciudad::create(['nombre' => 'BUGALAGRANDE', 'status' => true]);
        Ciudad::create(['nombre' => 'CAICEDONIA', 'status' => true]);
        Ciudad::create(['nombre' => 'CALIMA (DARIEN)', 'status' => true]);
        Ciudad::create(['nombre' => 'CANDELARIA', 'status' => true]);
        Ciudad::create(['nombre' => 'CARTAGO', 'status' => true]);
        Ciudad::create(['nombre' => 'DAGUA', 'status' => true]);
        Ciudad::create(['nombre' => 'EL AGUILA', 'status' => true]);
        Ciudad::create(['nombre' => 'EL CAIRO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL CERRITO', 'status' => true]);
        Ciudad::create(['nombre' => 'EL DOVIO', 'status' => true]);
        Ciudad::create(['nombre' => 'FLORIDA', 'status' => true]);
        Ciudad::create(['nombre' => 'GINEBRA', 'status' => true]);
        Ciudad::create(['nombre' => 'GUACARI', 'status' => true]);
        Ciudad::create(['nombre' => 'JAMUNDI', 'status' => true]);
        Ciudad::create(['nombre' => 'LA CUMBRE', 'status' => true]);
        Ciudad::create(['nombre' => 'LA UNION', 'status' => true]);
        Ciudad::create(['nombre' => 'LA VICTORIA', 'status' => true]);
        Ciudad::create(['nombre' => 'OBANDO', 'status' => true]);
        Ciudad::create(['nombre' => 'PALMIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'PRADERA', 'status' => true]);
        Ciudad::create(['nombre' => 'RESTREPO', 'status' => true]);
        Ciudad::create(['nombre' => 'RIOFRIO', 'status' => true]);
        Ciudad::create(['nombre' => 'ROLDANILLO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN PEDRO', 'status' => true]);
        Ciudad::create(['nombre' => 'SEVILLA', 'status' => true]);
        Ciudad::create(['nombre' => 'TORO', 'status' => true]);
        Ciudad::create(['nombre' => 'TRUJILLO', 'status' => true]);
        Ciudad::create(['nombre' => 'TULUA', 'status' => true]);
        Ciudad::create(['nombre' => 'ULLOA', 'status' => true]);
        Ciudad::create(['nombre' => 'VERSALLES', 'status' => true]);
        Ciudad::create(['nombre' => 'VIJES', 'status' => true]);
        Ciudad::create(['nombre' => 'YOTOCO', 'status' => true]);
        Ciudad::create(['nombre' => 'YUMBO', 'status' => true]);
        Ciudad::create(['nombre' => 'ZARZAL', 'status' => true]);
        Ciudad::create(['nombre' => 'ARAUCA', 'status' => true]);
        Ciudad::create(['nombre' =>'ARAUQUITA', 'status' => true]);
        Ciudad::create(['nombre' => 'CRAVO NORTE', 'status' => true]);
        Ciudad::create(['nombre' => 'FORTUL', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO RONDON', 'status' => true]);
        Ciudad::create(['nombre' => 'SARAVENA', 'status' => true]);
        Ciudad::create(['nombre' => 'TAME', 'status' => true]);
        Ciudad::create(['nombre' => 'YOPAL', 'status' => true]);
        Ciudad::create(['nombre' =>'AGUAZUL', 'status' => true]);
        Ciudad::create(['nombre' =>'CHAMEZA', 'status' => true]);
        Ciudad::create(['nombre' => 'HATO COROZAL', 'status' => true]);
        Ciudad::create(['nombre' => 'LA SALINA', 'status' => true]);
        Ciudad::create(['nombre' => 'MANI', 'status' => true]);
        Ciudad::create(['nombre' => 'MONTERREY', 'status' => true]);
        Ciudad::create(['nombre' => 'NUNCHIA', 'status' => true]);
        Ciudad::create(['nombre' => 'OROCUE', 'status' => true]);
        Ciudad::create(['nombre' => 'PAZ DE ARIPORO', 'status' => true]);
        Ciudad::create(['nombre' => 'PORE', 'status' => true]);
        Ciudad::create(['nombre' => 'RECETOR', 'status' => true]);
        Ciudad::create(['nombre' => 'SABANALARGA', 'status' => true]);
        Ciudad::create(['nombre' => 'SACAMA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN LUIS DE PALENQUE', 'status' => true]);
        Ciudad::create(['nombre' => 'TAMARA', 'status' => true]);
        Ciudad::create(['nombre' => 'TAURAMENA', 'status' => true]);
        Ciudad::create(['nombre' => 'TRINIDAD', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLANUEVA', 'status' => true]);
        Ciudad::create(['nombre' => 'MOCOA', 'status' => true]);
        Ciudad::create(['nombre' => 'COLON', 'status' => true]);
        Ciudad::create(['nombre' => 'ORITO', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO ASIS', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO CAICEDO', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO GUZMAN', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO LEGUIZAMO', 'status' => true]);
        Ciudad::create(['nombre' => 'SIBUNDOY', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN FRANCISCO', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN MIGUEL (LA DORADA)', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTIAGO', 'status' => true]);
        Ciudad::create(['nombre' => 'LA HORMIGA (VALLE DEL GUAMUEZ)', 'status' => true]);
        Ciudad::create(['nombre' => 'VILLAGARZON', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN ANDRES', 'status' => true]);
        Ciudad::create(['nombre' => 'PROVIDENCIA', 'status' => true]);
        Ciudad::create(['nombre' => 'LETICIA', 'status' => true]);
        Ciudad::create(['nombre' => 'EL ENCANTO', 'status' => true]);
        Ciudad::create(['nombre' => 'LA CHORRERA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA PEDRERA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA VICTORIA', 'status' => true]);
        Ciudad::create(['nombre' => 'MIRITI-PARANA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO ALEGRIA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO ARICA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO NARIÑO', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO SANTANDER', 'status' => true]);
        Ciudad::create(['nombre' => 'TARAPACA', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO INIRIDA', 'status' => true]);
        Ciudad::create(['nombre' => 'BARRANCO MINAS', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN FELIPE', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO COLOMBIA', 'status' => true]);
        Ciudad::create(['nombre' => 'LA GUADALUPE', 'status' => true]);
        Ciudad::create(['nombre' => 'CACAHUAL', 'status' => true]);
        Ciudad::create(['nombre' => 'PANA PANA (CAMPO ALEGRE)', 'status' => true]);
        Ciudad::create(['nombre' => 'MORICHAL (MORICHAL NUEVO)', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JOSE DEL GUAVIARE', 'status' => true]);
        Ciudad::create(['nombre' => 'CALAMAR', 'status' => true]);
        Ciudad::create(['nombre' => 'EL RETORNO', 'status' => true]);
        Ciudad::create(['nombre' => 'MIRAFLORES', 'status' => true]);
        Ciudad::create(['nombre' => 'MITU', 'status' => true]);
        Ciudad::create(['nombre' => 'CARURU', 'status' => true]);
        Ciudad::create(['nombre' => 'PACOA', 'status' => true]);
        Ciudad::create(['nombre' => 'TARAIRA', 'status' => true]);
        Ciudad::create(['nombre' => 'PAPUNAUA (MORICHAL)', 'status' => true]);
        Ciudad::create(['nombre' => 'YAVARATE', 'status' => true]);
        Ciudad::create(['nombre' => 'PUERTO CARREÑO', 'status' => true]);
        Ciudad::create(['nombre' => 'LA PRIMAVERA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA RITA', 'status' => true]);
        Ciudad::create(['nombre' => 'SANTA ROSALIA', 'status' => true]);
        Ciudad::create(['nombre' => 'SAN JOSE DE OCUNE', 'status' => true]);
        Ciudad::create(['nombre' => 'CUMARIBO', 'status' => true]);
    }
}
